name: Create Release

on: 
  workflow_run:
    workflows: [Update for Release]
    types:
      - completed
  workflow_dispatch:

jobs:
  update:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        uses: mwbowers/vs-project-version@v1.0.3
        with:
          PROJ_PATH: PdbFixer.csproj
          VER_PLACES: 3
        
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: |
            Changes in this Release
            - Working on change list. Check back soon.
          draft: false
          prerelease: true
