name: Update for Release

on: 
  workflow_dispatch:
    inputs:
      releaseType: 
        type: choice
        description: Type of Release
        options:
        - Build
        - Minor
        - Major

jobs:
  update:
    name: Update for Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PACKAGE }}
          
      - name: Get version
        id: get_version
        uses: mwbowers/vs-project-version@v1.0.3
        with:
          PROJ_PATH: Microsoft.Cci.Ast/Microsoft.Cci.Ast.csproj
          VER_PLACES: 3
          
      - name: Increment version
        id: increment_version
        uses: mwbowers/IncrementVersion@v1.0.1
        with:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          INCREMENT_POSITION: ${{ github.event.inputs.releaseType == 'Major' && 1 || github.event.inputs.releaseType == 'Minor' && 2 || 3 }}

      - name: Replace version
        run: find -name *.csproj -print -exec sed -i 's/\(<Version.*>\)\(.*\)\(<\/Version>\)/\1${{ steps.increment_version.outputs.VERSION }}\3/' {} \;

      - name: Commit changes
        run: |
          git config --global user.name '${{ secrets.GH_USER }}'
          git config --global user.email '${{ secrets.GH_USEREMAIL }}'
          git commit -am "Version increment"
          git push
